### ISSUE TITLE
Must persist counter across restarts

### ISSUE THREAD

**Issue by JaviVM00** [JaviVM00/lab-agile-planning#3]
**As a**  Service administrator
 **I need**  the counter to persist
 **So that** I can keep  counter values in case  of restart
   
 ### Details and Assumptions
 * We will use a Redis database
 *  Counter will be store as a name-value pair
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I have incremented the counter to 2 
 When I restart the service
 Then the counter should still return 2 
 ```

**Comment by JVM00** [comment]
Comment
