### ISSUE TITLE
Deploy service to the Cloud

### ISSUE THREAD

**Issue by JaviVM00** [JaviVM00/lab-agile-planning#5]
**As a**  Developer
 **I need** to be able to deploy the service to the cloud
 **So that** I can run the service by a thid cloud provider
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by JVM00** [comment]
Comment
